# Generated by Django 4.0.5 on 2022-07-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('cat', models.CharField(max_length=50, null=True)),
                ('ope_time', models.CharField(max_length=100, null=True)),
                ('rec_time', models.CharField(max_length=50, null=True)),
                ('addrs', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripadvisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=5)),
                ('date', models.CharField(max_length=10)),
                ('member', models.CharField(max_length=20, null=True)),
                ('review', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripdotComReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=5)),
                ('date', models.CharField(max_length=10)),
                ('review', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
