# Generated by Django 4.0.5 on 2022-07-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripadvisorReview',
        ),
        migrations.DeleteModel(
            name='TripdotComReview',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='cat',
            new_name='category',
        ),
    ]
