# Generated by Django 4.0.5 on 2022-07-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_delete_tripadvisorreview_delete_tripdotcomreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=5, null=True)),
                ('year', models.CharField(max_length=5, null=True)),
                ('month', models.CharField(max_length=5, null=True)),
                ('day', models.CharField(max_length=4, null=True)),
                ('review', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
